apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: bookmark
type: Opaque
# Base64 encoded values (recommended for production)
data:
  username: Ym9va21hcmt1c2Vy
  password: Ym9va21hcmtwYXNz
